GET http://localhost:5000/api/v1/tracks/all

###

GET http://localhost:5000/api/v1/tracks/geojson/60c6008b56ee823804eccfe0
Content-Type: application/json

# {
#   "id": "60b26fbc0cd66445666f6408"
# }

###

PATCH http://localhost:5000/api/v1/tracks/edit/name/60c6008b56ee823804eccfe1
Content-Type: application/json

{
  "name": "abc track 9"
}

###

GET http://localhost:5000

###

POST http://localhost:5000/api/v1/tracks/addFile


###

PATCH http://localhost:5000/api/v1/features/edit/name/60d0fa90fdd65e31aad6ab9c/76d48f1a-9452-48e4-9485-fa1f87c20d04
Content-Type: application/json

{
  "name": "abc track 9"
}

###